services:
  app:
    build:
      target: production

  db:
    volumes:
      - gfb_postgresql_data:/var/lib/postgresql/data

  proxy:
    build:
      context: ../../
      dockerfile: build/docker/nginx.Dockerfile
    volumes:
      - ../../configs/nginx:/etc/nginx/conf.d:Z

volumes:
  gfb_postgresql_data:
