name: gfb-dev

services:
  app:
    build:
      target: development
    env_file:
      - ../../.env
    volumes:
      - gfb_mod_cache:/go/pkg/mod
      - gfb_build_cache:/root/.cache/go-build
      - ../../.:/app:Z
    ports:
      - 3000:${SERVER_PORT}

  proxy:
    volumes:
      - ../../configs/nginx:/etc/nginx/conf.d:Z
      - ../../build/docker/scripts/start-nginx.sh:/start-nginx.sh:Z
      - ../../web/static:/usr/share/nginx/html:Z
