services:
  app:
    build:
      target: production
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://app:${SERVER_PORT}/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    volumes:
      - gfb_postgresql_data:/var/lib/postgresql/data
      - ../../configs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:Z
      - ../../configs/postgres/psqlrc:/root/.psqlrc:Z

  proxy:
    build:
      context: ../../
      dockerfile: build/docker/nginx.Dockerfile
    volumes:
      - ../../configs/nginx:/etc/nginx/conf.d:Z
    depends_on:
      app:
        condition: service_healthy

volumes:
  gfb_postgresql_data:
