name: gfb-dev

services:
  app:
    build:
      target: development
    env_file:
      - ../../.env
    volumes:
      - gfb_mod_cache:/go/pkg/mod:Z
      - ../../.:/app:Z
    ports:
      - 3000:${SERVER_PORT}

  proxy:
    volumes:
      - ../../configs/nginx.conf.template:/etc/nginx/nginx.conf.template:Z
      - ../../web/static:/usr/share/nginx/html:Z
      - ../../build/docker/scripts/start-nginx.sh:/start-nginx.sh:Z
