name: gfb-test

services:
  app:
    build:
      context: ../../
      dockerfile: build/docker/Dockerfile
      target: testing
    container_name: gfb-test-app
    env_file:
      - ../../.env.testing
    volumes:
      - gfb_test_mod_cache:/go/pkg/mod:Z
      - ../../.:/test:Z

volumes:
  gfb_test_mod_cache:
