name: Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-checks:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...

      - name: Check for outdated dependencies
        run: go list -m -u all

      - name: Install docker-compose
        run: |
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.32.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker Compose services
        run: |
          docker-compose -f deployments/docker-compose/compose.yml build

      - name: Container scanning with Trivy for app service
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "image"
          image-ref: "gfb-app:latest"

      - name: Container scanning with Trivy for the db service
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "image"
          image-ref: "gfb-db:latest"

      - name: Container scanning with Trivy for the proxy service
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "image"
          image-ref: "gfb-proxy:latest"

      - name: Container scanning with Trivy for the migrate service
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "image"
          image-ref: "gfb-migrate:latest"

      - name: Dependabot alerts (Optional)
        uses: dependabot/fetch-metadata@v1
        with:
          package-ecosystem: "gomod"
          directory: "/"
