name: Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-checks:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...

      - name: Check for outdated dependencies
        run: go list -m -u all

      - name: Check if Dockerfile exists in subdirectory
        id: dockerfile-check
        run: |
          if [ -f "build/docker/Dockerfile" ]; then
            echo "Dockerfile found in build/docker/ directory"
            echo "dockerfile_exists=true" >> $GITHUB_ENV
          else
            echo "Dockerfile not found"
            echo "dockerfile_exists=false" >> $GITHUB_ENV

      - name: Container scanning with Trivy
        if: env.dockerfile_exists == 'true'
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          severity: "CRITICAL,HIGH"
          context: "docker"

      - name: Dependabot alerts (Optional)
        uses: dependabot/fetch-metadata@v1
        with:
          package-ecosystem: "gomod"
          directory: "/"
